routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminProfile\NavbarController;
use App\Http\Controllers\AdminProfile\ContentController;
use App\Http\Controllers\AdminProfile\NavbarContentController;
use App\Http\Controllers\AdminProfile\NewsController;
use App\Http\Controllers\AdminProfile\BannerController;
use App\Http\Controllers\AdminProfile\UserController;
use App\Http\Controllers\AdminProfile\FiledownloadController;
use App\Http\Controllers\AdminProfile\DashboardController;
use App\Http\Controllers\FrontendProfile\PageController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });
Route::get('/', [HomeController::class, 'index'])->name('dashboard');
Route::get('/admin', [DashboardController::class, 'index'])->name('admin.dashboard');
Route::get('/page/{URI}', [PageController::class, 'show'])->name('page');

// Route::get('/admin2', function () {
//     return view('admin-profile.home');
// });

// Route for ADMIN PROFILE
Route::prefix('admin')->name('admin.')->group(function () {
    Route::resource('navbars', NavbarController::class);
    Route::resource('contents', ContentController::class);
    Route::prefix('navbar')->name('navbars.')->group(function () {
        Route::resource('contents', NavbarContentController::class);
    });
    Route::resource('news', NewsController::class);
    Route::resource('banners', BannerController::class);
    Route::resource('filedownloads', FiledownloadController::class);
    Route::resource('users', UserController::class);
});


// Route for ADMIN
// Route::prefix('admin')->name('admin.')->middleware('auth', 'verified', 'role:admin')->group(function () {
//     Route::get('/', function () {
//         return view('admin.index');
//     });
//     Route::get('/grade', function () {
//         return view('admin.grade.index');
//     });
//     Route::get('/school-years', function () {
//         return view('admin.grade.schoolYears');
//     });
//     Route::get('/nationality', function () {
//         return view('admin.grade.nationality');
//     });
    
//     Route::get('/addcandidate', function () {
//         return view('admin.students.addcandidate');
//     });
//     Route::get('/candidate', function () {
//         return view('admin.students.candidate');
//     });
//     Route::get('/editcandidate', function () {
//         return view('admin.students.editCandidate');
//     });
//     Route::get('/detailscandidate', function () {
//         return view('admin.students.detailsCandidate');
//     });  
    
    
//     Route::get('/student-information', function () {
//         return view('admin.students.studentInformation');
//     });
//     Route::get('/details-student-information', function () {
//         return view('admin.students.detailsStudentInformation');
//     });
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/AdminProfile/BannerController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Banner;
use Illuminate\Support\Facades\Storage;


class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $banners = Banner::orderBy('created_at', 'desc')->get();
        return view('admin-profile.banners.index', compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.banners.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'sequence' => 'required',
        ]);
        
        $this->validate($request, ['image' => 'required|image']);
        if($request->hasfile('image'))
        {
            $path = Storage::disk('s3')->put('images', $request->image, 'public');
            $path = Storage::disk('s3')->url($path);
            $request['image'] = $request->image->getClientOriginalName();
            $request['file_path'] = $path;
            Banner::create($request->all());
            return redirect()->route('admin.banners.index')
                    ->with('success', 'Banners created successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/ContentController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Content;
use Illuminate\Support\Str;
class ContentController extends Controller
{
    public function index()
    {
        $contents = Content::get();
        // dd($navbars);
        return view('admin-profile.contents.index', compact('contents'));
    }
}

app/Http/Controllers/AdminProfile/DashboardController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    public function index()
    {
        return view('admin-profile.home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/FileDownloadController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\FileDownload;
use Illuminate\Support\Facades\Storage;

class FileDownloadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $filedownloads = FileDownload::orderBy('created_at', 'desc')->get();
        return view('admin-profile.filedownloads.index', compact('filedownloads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.filedownloads.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        // dd($request->all());
        $this->validate($request, ['file' => 'required|mimes:pdf|max:10000']);
        if($request->hasfile('file'))
        {
            $path = Storage::disk('s3')->put('downloads', $request->file, 'public');
            $path = Storage::disk('s3')->url($path);
            $request['file'] = $request->file->getClientOriginalName();
            $request['file_path'] = $path;
            FileDownload::create($request->all());
            return redirect()->route('admin.filedownloads.index')
                    ->with('success', 'File Download created successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/NavbarContentController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use App\Models\Navbar;
use App\Models\NavbarContent;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class NavbarContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contents = NavbarContent::all();
        return view('admin-profile.navbar-contents.index', compact('contents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $navbarUrls = $this->getNavbarUrls();
        return view('admin-profile.navbar-contents.create', compact('navbarUrls'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);        
        $request['slug'] = Str::slug($request['title']);
        NavbarContent::create($request->all());
        return redirect()->route('admin.navbars.contents.index')
                ->with('success', 'Navbar Content created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function show(NavbarContent $navbarContent)
    {
        return view('admin-profile.navbar-contents.show', compact('navbarContent'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function edit(NavbarContent $navbarContent, $id)
    {
        $navbarContent = NavbarContent::find($id);
        $navbarUrls = $this->getNavbarUrls();

        return view('admin-profile.navbar-contents.edit', compact('navbarContent', 'navbarUrls'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
        ]);
        $request['slug'] = Str::slug($request['title']);
        $navbarContent = NavbarContent::find($id);
        $navbarContent->update($request->all());
        $status = array(
            'class' => "alert-success",
            'message' => "Navbar Content updated successfully"
        );
        return redirect()->route('admin.navbars.contents.index')
            ->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function destroy(NavbarContent $navbarContent)
    {
        $navbarContent->delete();

        return redirect()->route('admin.navbars.contents.index')
            ->with('success', 'Navbar Content deleted successfully');
    }

    private function getNavbarUrls(){
        $navbars = Navbar::whereNull('parent_id')->get();
        $navbarUrls = collect();
        foreach ($navbars as $navbar) {
            // dd($navbar->children()->count());
            if($navbar->children()->get()->count() > 0){
                $navbarChildren = $navbar->children()->get();
                foreach ($navbarChildren as $navbarChild) {
                    $data = array(
                        'id' => $navbarChild->id,
                        'url' => '/'.$navbar->slug.'/'.$navbarChild->slug
                    );
                    $navbarUrls->push((object)$data);
                }
            }
            if($navbar->children()->get()->count() == 0){
                $data = array(
                    'id' => $navbar->id,
                    'url' => '/'.$navbar->slug
                );
                $navbarUrls->push((object)$data);
            }
        }
        return $navbarUrls;
    }
}

app/Http/Controllers/AdminProfile/NewsController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderBy('created_at', 'desc')->get();
        return view('admin-profile.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        
        $request['slug'] = Str::slug($request['title']);
        News::create($request->all());
        return redirect()->route('admin.news.index')
                ->with('success', 'News created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {        
        return view('admin-profile.news.show', compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        return view('admin-profile.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $request['slug'] = Str::slug($request['title']);
        $news->update($request->all());
        $status = array(
            'class' => "alert-success",
            'message' => "News updated successfully"
        );
        return redirect()->route('admin.news.index')
            ->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();

        return redirect()->route('admin.news.index')
            ->with('success', 'News deleted successfully');
    }
}

resources/views/admin-profile/navbars/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminSGIA - Navbar')
@section('plugins.Datatables', true)

{{-- Setup data for datatables --}}
@php
$heads = [
    'ID',
    'Title',
    ['label' => 'Positions', 'no-export' => true, 'width' => 5],
    ['label' => 'Actions', 'no-export' => true, 'width' => 5],
];
$data = array();
foreach ($navbars as $navbar) {
    $seqUp = (int)$navbar->sequence-1;
    $seqDown = (int)$navbar->sequence+1;
    $btnEdit = '<button class="btn btn-xs btn-default text-primary mx-1 shadow" title="Edit" data-toggle="modal" data-target="#modalEditNavbar'.$navbar->id.'">
                    <i class="fa fa-lg fa-fw fa-pen"></i>
                </button>';
    $btnDelete = '<button class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                    <i class="fa fa-lg fa-fw fa-trash"></i>
                </button>';
    $btnDetails = '<a href="'.route('admin.navbars.show', $navbar).'" class="btn btn-xs btn-default text-teal mx-1 shadow"><i class="fa fa-lg fa-fw fa-eye"></i></a>';
    $btnMoveUp = '<button class="btn btn-xs btn-default text-teal mx-1 shadow btn-move-up" title="Details" data-sequence="'.$seqUp.'" data-navbar="'.$navbar->id.'">
                    <i class="fas fa-lg fa-fw fa-chevron-up"></i>
                </button>';
    $btnMoveDown = '<button class="btn btn-xs btn-default text-teal mx-1 shadow btn-move-down" title="Details" data-sequence="'.$seqDown.'" data-navbar="'.$navbar->id.'">
                    <i class="fas fa-lg fa-fw fa-chevron-down"></i>
                </button>';
    $formUpdateNavbar = '<form id="updateNavbar_'.$navbar->id.'" action='.route("admin.navbars.update", $navbar).' method="POST">
                        '.csrf_field().'
                        <input type="hidden" name="_method" value="PUT" />
                        <input type="hidden" name="sequence"/>
                        <input type="hidden" name="title" value="'.$navbar->title.'">
                    </form>';
    $modalEdit = '<div class="modal fade" id="modalEditNavbar'.$navbar->id.'" data-backdrop="static" data-keyboard="false">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
                        <div class="modal-content">
                            <div class="modal-header bg-teal">
                                <h4 class="modal-title">
                                    <i class="fas fa-plus mr-2"></i> Edit Navbar            
                                </h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <form action='.route("admin.navbars.update", $navbar).' method="POST" id="formEditNavbar'.$navbar->id.'">
                                <div class="modal-body">
                                    '.csrf_field().'
                                    <input type="hidden" name="_method" value="PUT" />
                                    <input type="hidden" name="sequence" value="'.$navbar->sequence.'">
                                    <div class="row">
                                        <div class="form-group col-md-12">
                                            <label for="title"> Title </label>
                                            <div class="input-group">
                                                <input id="title" name="title" class="form-control" placeholder="Enter Title" value="'.$navbar->title.'">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    <div class="modal-footer">
                                    <button type="submit" class="btn btn-success mr-auto submit-edit-navbar"> Save </button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal"> Discard </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>';
    $bar = array(
        $navbar->sequence, 
        $navbar->title,
        '<nobr>'.$btnMoveUp.$btnMoveDown.$formUpdateNavbar.'</nobr>',
        '<nobr>'.$btnEdit.$btnDelete.$btnDetails.$modalEdit.'</nobr>'
    );
    $data[] = $bar;
}


$config = [
    'data' => $data,
    'order' => [[1, 'asc']],
    'columns' => [null, null, ['orderable' => false]],
];
// dd($config['data']);
@endphp

@section('content_header')
    {{-- <h1>Navbars</h1> --}}
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Navbars</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active">Navbars</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    @if (session('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert {{ session('class') }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('message') }}
                </div>
            </div>
        </div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Navbar List</h3>
                    <div class="card-tools">
                        <x-adminlte-button label="Add Navbar" data-toggle="modal" data-target="#modalCreateNavbar" class="bg-teal"/>
                    </div>
                </div>
                <!-- ./card-header -->
                <div class="card-body">
                    <x-adminlte-datatable id="table1" :heads="$heads">
                        @foreach($config['data'] as $row)
                            <tr>
                                @foreach($row as $cell)
                                    <td>{!! $cell !!}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    </x-adminlte-datatable>
                    {{-- Modal Create --}}
                    <x-adminlte-modal id="modalCreateNavbar" title="Add New Navbar" size="lg" theme="teal"
                    icon="fas fa-plus" v-centered static-backdrop scrollable>
                        <form action="{{ route('admin.navbars.store') }}" method="POST" id="formCreateNavbar">
                            {{ csrf_field() }}
                            <div class="row">
                                <x-adminlte-input name="title" label="Title" placeholder="Enter Title" fgroup-class="col-md-12" disable-feedback/>
                            </div>
                        </form>
                        <x-slot name="footerSlot">
                            <x-adminlte-button class="mr-auto submit-create-navbar" theme="success" type="submit" label="Save"/>
                            <x-adminlte-button theme="danger" label="Discard" data-dismiss="modal"/>
                        </x-slot>
                    </x-adminlte-modal>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
@stop

@section('js')
    <script>
        $(document).ready(function(){
            $(".submit-create-navbar").click(function(){        
                $("#formCreateNavbar").submit(); // Submit the form
            });
            $(".btn-move-up").click(function(){      
                var position = $(this).attr('data-sequence');
                var navbarId = $(this).attr('data-navbar');
                $("input[name='sequence']").val(position);
                $('#updateNavbar_'+navbarId).submit();
            });
            $(".btn-move-down").click(function(){      
                var position = $(this).attr('data-sequence');
                var navbarId = $(this).attr('data-navbar');
                console.log(navbarId, position);
                $("input[name='sequence']").val(position);
                $('#updateNavbar_'+navbarId).submit();
            });
        });
    </script>
@stop