routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminProfile\NavbarController;
use App\Http\Controllers\AdminProfile\ContentController;
use App\Http\Controllers\AdminProfile\NavbarContentController;
use App\Http\Controllers\AdminProfile\NewsController;
use App\Http\Controllers\AdminProfile\BannerController;
use App\Http\Controllers\AdminProfile\UserController;
use App\Http\Controllers\AdminProfile\FiledownloadController;
use App\Http\Controllers\AdminProfile\DashboardController;
use App\Http\Controllers\FrontendProfile\PageController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });
Route::get('/', [HomeController::class, 'index'])->name('dashboard');
Route::get('/admin', [DashboardController::class, 'index'])->name('admin.dashboard');
Route::get('/page/{URI}', [PageController::class, 'show'])->name('page');

// Route::get('/admin2', function () {
//     return view('admin-profile.home');
// });

// Route for ADMIN PROFILE
Route::prefix('admin')->name('admin.')->group(function () {
    Route::resource('navbars', NavbarController::class);
    Route::resource('contents', ContentController::class);
    Route::prefix('navbar')->name('navbars.')->group(function () {
        Route::resource('contents', NavbarContentController::class);
    });
    Route::resource('news', NewsController::class);
    Route::resource('banners', BannerController::class);
    Route::resource('filedownloads', FiledownloadController::class);
    Route::resource('users', UserController::class);
});


// Route for ADMIN
// Route::prefix('admin')->name('admin.')->middleware('auth', 'verified', 'role:admin')->group(function () {
//     Route::get('/', function () {
//         return view('admin.index');
//     });
//     Route::get('/grade', function () {
//         return view('admin.grade.index');
//     });
//     Route::get('/school-years', function () {
//         return view('admin.grade.schoolYears');
//     });
//     Route::get('/nationality', function () {
//         return view('admin.grade.nationality');
//     });
    
//     Route::get('/addcandidate', function () {
//         return view('admin.students.addcandidate');
//     });
//     Route::get('/candidate', function () {
//         return view('admin.students.candidate');
//     });
//     Route::get('/editcandidate', function () {
//         return view('admin.students.editCandidate');
//     });
//     Route::get('/detailscandidate', function () {
//         return view('admin.students.detailsCandidate');
//     });  
    
    
//     Route::get('/student-information', function () {
//         return view('admin.students.studentInformation');
//     });
//     Route::get('/details-student-information', function () {
//         return view('admin.students.detailsStudentInformation');
//     });
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/AdminProfile/BannerController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Banner;
use Illuminate\Support\Facades\Storage;


class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $banners = Banner::orderBy('created_at', 'desc')->get();
        return view('admin-profile.banners.index', compact('banners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.banners.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'sequence' => 'required',
        ]);
        
        $this->validate($request, ['image' => 'required|image']);
        if($request->hasfile('image'))
        {
            $path = Storage::disk('s3')->put('images', $request->image, 'public');
            $path = Storage::disk('s3')->url($path);
            $request['image'] = $request->image->getClientOriginalName();
            $request['file_path'] = $path;
            Banner::create($request->all());
            return redirect()->route('admin.banners.index')
                    ->with('success', 'Banners created successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/ContentController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Content;
use Illuminate\Support\Str;
class ContentController extends Controller
{
    public function index()
    {
        $contents = Content::get();
        // dd($navbars);
        return view('admin-profile.contents.index', compact('contents'));
    }
}

app/Http/Controllers/AdminProfile/DashboardController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    public function index()
    {
        return view('admin-profile.home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/FileDownloadController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\FileDownload;
use Illuminate\Support\Facades\Storage;

class FileDownloadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $filedownloads = FileDownload::orderBy('created_at', 'desc')->get();
        return view('admin-profile.filedownloads.index', compact('filedownloads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.filedownloads.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        // dd($request->all());
        $this->validate($request, ['file' => 'required|mimes:pdf|max:10000']);
        if($request->hasfile('file'))
        {
            $path = Storage::disk('s3')->put('downloads', $request->file, 'public');
            $path = Storage::disk('s3')->url($path);
            $request['file'] = $request->file->getClientOriginalName();
            $request['file_path'] = $path;
            FileDownload::create($request->all());
            return redirect()->route('admin.filedownloads.index')
                    ->with('success', 'File Download created successfully.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/AdminProfile/NavbarContentController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use App\Models\Navbar;
use App\Models\NavbarContent;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class NavbarContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contents = NavbarContent::all();
        return view('admin-profile.navbar-contents.index', compact('contents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $navbarUrls = $this->getNavbarUrls();
        return view('admin-profile.navbar-contents.create', compact('navbarUrls'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);        
        $request['slug'] = Str::slug($request['title']);
        NavbarContent::create($request->all());
        return redirect()->route('admin.navbars.contents.index')
                ->with('success', 'Navbar Content created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function show(NavbarContent $navbarContent)
    {
        return view('admin-profile.navbar-contents.show', compact('navbarContent'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function edit(NavbarContent $navbarContent, $id)
    {
        $navbarContent = NavbarContent::find($id);
        $navbarUrls = $this->getNavbarUrls();

        return view('admin-profile.navbar-contents.edit', compact('navbarContent', 'navbarUrls'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
        ]);
        $request['slug'] = Str::slug($request['title']);
        $navbarContent = NavbarContent::find($id);
        $navbarContent->update($request->all());
        $status = array(
            'class' => "alert-success",
            'message' => "Navbar Content updated successfully"
        );
        return redirect()->route('admin.navbars.contents.index')
            ->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\NavbarContent  $navbarContent
     * @return \Illuminate\Http\Response
     */
    public function destroy(NavbarContent $navbarContent)
    {
        $navbarContent->delete();

        return redirect()->route('admin.navbars.contents.index')
            ->with('success', 'Navbar Content deleted successfully');
    }

    private function getNavbarUrls(){
        $navbars = Navbar::whereNull('parent_id')->get();
        $navbarUrls = collect();
        foreach ($navbars as $navbar) {
            // dd($navbar->children()->count());
            if($navbar->children()->get()->count() > 0){
                $navbarChildren = $navbar->children()->get();
                foreach ($navbarChildren as $navbarChild) {
                    $data = array(
                        'id' => $navbarChild->id,
                        'url' => '/'.$navbar->slug.'/'.$navbarChild->slug
                    );
                    $navbarUrls->push((object)$data);
                }
            }
            if($navbar->children()->get()->count() == 0){
                $data = array(
                    'id' => $navbar->id,
                    'url' => '/'.$navbar->slug
                );
                $navbarUrls->push((object)$data);
            }
        }
        return $navbarUrls;
    }
}

app/Http/Controllers/AdminProfile/NewsController.php
<?php

namespace App\Http\Controllers\AdminProfile;

use App\Http\Controllers\Controller;
use App\Models\News;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = News::orderBy('created_at', 'desc')->get();
        return view('admin-profile.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin-profile.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
        ]);
        
        $request['slug'] = Str::slug($request['title']);
        News::create($request->all());
        return redirect()->route('admin.news.index')
                ->with('success', 'News created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {        
        return view('admin-profile.news.show', compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        return view('admin-profile.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title' => 'required',
        ]);

        $request['slug'] = Str::slug($request['title']);
        $news->update($request->all());
        $status = array(
            'class' => "alert-success",
            'message' => "News updated successfully"
        );
        return redirect()->route('admin.news.index')
            ->with($status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        $news->delete();

        return redirect()->route('admin.news.index')
            ->with('success', 'News deleted successfully');
    }
}

resources/views/admin-profile/navbar-contents/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminSGIA - Add Navbar Content')
@section('plugins.Summernote', true)
@section('plugins.Select2', true)
{{-- @section('plugins.BsCustomFileInput', true) --}}

@section('content_header')
    {{-- <h1>Navbars</h1> --}}
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Add New Navbar Contents</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.navbars.index')}}">Navbars</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.navbars.contents.index')}}">Contents</a></li>
            <li class="breadcrumb-item active">Add New</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    @if (session('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert {{ session('class') }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('message') }}
                </div>
            </div>
        </div>
    @endif
@stop

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('admin.navbars.contents.store')}}" method="POST">
                    @csrf
                    {{-- Input Navbar --}}
                    <x-adminlte-select2 name="navbar_id" label="Navbar URL">
                        @foreach ($navbarUrls as $navbarUrl)
                            <option value="{{$navbarUrl->id}}">{{$navbarUrl->url}}</option>                            
                        @endforeach
                    </x-adminlte-select2>
                    {{-- Input Title --}}
                    <x-adminlte-input name="title" label="Title" placeholder="Enter Title"/>
                    {{-- Input Content Link --}}
                    {{-- <x-adminlte-input name="content" label="Content" placeholder="Enter Link"/> --}}
                    {{-- Input Content Type --}}
                    <x-adminlte-select2 name="content_type" label="Content Type">
                        <option value="text">Text</option>
                        <option value="image">Image</option>
                        <option value="file">File</option>
                        <option value="link">Link</option>
                    </x-adminlte-select2>
                    {{-- Input Content Text --}}
                    <x-adminlte-text-editor label="Content" name="content"/>
                    <div class="text-right">
                        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>

@stop

@section('css')
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
@stop

@section('js')
    <script>
        $(document).ready(function(){
            $("select[name='content_type']").on('change', function() {
                console.log(this.value);
            });;
            
        });
    </script>
@stop

resources/views/admin-profile/navbar-contents/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminSGIA - Edit Navbar Content')
@section('plugins.Summernote', true)
@section('plugins.Select2', true)
{{-- @section('plugins.BsCustomFileInput', true) --}}

@section('content_header')
    {{-- <h1>Navbars</h1> --}}
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Edit Navbar Contents</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.navbars.index')}}">Navbars</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.navbars.contents.index')}}">Contents</a></li>
            <li class="breadcrumb-item active">Edit</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    @if (session('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert {{ session('class') }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('message') }}
                </div>
            </div>
        </div>
    @endif
@stop

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('admin.navbars.contents.update', $navbarContent)}}" method="POST">
                    @csrf
                    @method('PUT')
                    {{-- Input Navbar --}}
                    <x-adminlte-select2 name="navbar_id" label="Navbar URL">
                        @foreach ($navbarUrls as $navbarUrl)
                            <option value="{{$navbarUrl->id}}" {{$navbarContent->navbar_id == $navbarUrl->id ? 'selected': ''}}>{{$navbarUrl->url}}</option>                            
                        @endforeach
                    </x-adminlte-select2>
                    {{-- Input Title --}}
                    <x-adminlte-input name="title" label="Title" placeholder="Enter Title" value="{{$navbarContent->title}}"/>
                    {{-- Input Content Link --}}
                    {{-- <x-adminlte-input name="content" label="Content" placeholder="Enter Link"/> --}}
                    {{-- Input Content Type --}}
                    <x-adminlte-select2 name="content_type" label="Content Type">
                        <option value="text" {{$navbarContent->content_type == 'text' ? 'selected': ''}}>Text</option>
                        <option value="image" {{$navbarContent->content_type == 'image' ? 'selected': ''}}>Image</option>
                        <option value="file" {{$navbarContent->content_type == 'file' ? 'selected': ''}}>File</option>
                        <option value="link" {{$navbarContent->content_type == 'link' ? 'selected': ''}}>Link</option>
                    </x-adminlte-select2>
                    {{-- Input Content Text --}}
                    <x-adminlte-text-editor label="Content" name="content">
                        {!!$navbarContent->content!!}
                    </x-adminlte-text-editor>
                    <div class="text-right">
                        <x-adminlte-button class="btn-flat" type="submit" label="Submit" theme="success" icon="fas fa-lg fa-save"/>
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>

@stop

@section('css')
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
@stop

@section('js')
    <script>
        $(document).ready(function(){
            $("select[name='content_type']").on('change', function() {
                console.log(this.value);
            });;
            
        });
    </script>
@stop

resources/views/admin-profile/navbar-contents/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminSGIA - Navbar Content')
@section('plugins.Datatables', true)

{{-- Setup data for datatables --}}
@php
$heads = [
    'ID',
    'Navbar',
    'Title',
    ['label' => 'Actions', 'no-export' => true, 'width' => 5],
];
$data = array();
$i = 1;
foreach ($contents as $content) {
    $btnEdit = '<a href="'.route('admin.navbars.contents.edit', $content).'" class="btn btn-xs btn-default text-teal mx-1 shadow"><i class="fa fa-lg fa-fw fa-pen"></i></a>';
    $btnDelete = '<button class="btn btn-xs btn-default text-danger mx-1 shadow" title="Delete">
                    <i class="fa fa-lg fa-fw fa-trash"></i>
                </button>';
    $btnDetails = '<a href="'.route('admin.navbars.contents.show', $content).'" class="btn btn-xs btn-default text-teal mx-1 shadow"><i class="fa fa-lg fa-fw fa-eye"></i></a>';

    $navbar = $content->navbar;
    $navbarParent = $content->navbar->parent()->first();
    $navbarSlug = isset($navbarParent) ? '/'.$navbarParent->slug.'/'.$navbar->slug : '/'.$navbar->slug;
    // dd($navbarSlug);
    
    
    $bar = array(
        $i,
        $navbarSlug,
        $content->title,
        '<nobr>'.$btnEdit.$btnDelete.$btnDetails.'</nobr>'
    );
    $data[] = $bar;
    $i += 1;
}


$config = [
    'data' => $data,
    'order' => [[1, 'asc']],
    'columns' => [null, null, ['orderable' => false]],
];
// dd($config['data']);
@endphp

@section('content_header')
    {{-- <h1>Navbars</h1> --}}
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0">Navbar Contents</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{route('admin.navbars.index')}}">Navbars</a></li>
            <li class="breadcrumb-item active">Contents</li>
            </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    @if (session('message'))
        <div class="row">
            <div class="col-md-12">
                <div class="alert {{ session('class') }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ session('message') }}
                </div>
            </div>
        </div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Navbar Content List</h3>
                    <div class="card-tools">
                        <a href="{{route('admin.navbars.contents.create')}}" class="btn btn-default bg-teal">Add Content</a>
                    </div>
                </div>
                <!-- ./card-header -->
                <div class="card-body">
                    <x-adminlte-datatable id="table1" :heads="$heads">
                        @foreach($config['data'] as $row)
                            <tr>
                                @foreach($row as $cell)
                                    <td>{!! $cell !!}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    </x-adminlte-datatable>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    {{-- <link rel="stylesheet" href="/css/admin_custom.css"> --}}
@stop

@section('js')
    <script>
        $(document).ready(function(){
            
        });
    </script>
@stop